selector:
  type: ['PosteriorBasedSelectorJoint']
  model_name: 'Coteaching'
  model_config_path: 'AL_cleaning/configs/models/benchmark_3_idn/b3_co_teaching_v5_res50.yaml'
  # use_active_relabelling: True
  output_directory: 'SelectorResults/cifar10idn/co_teaching/val'

