selector:
  type: ['PosteriorBasedSelectorJoint']
  model_name: 'Vanilla'
  model_config_path: 'AL_cleaning/configs/models/benchmark_3_idn/b3_vanilla_res50.yaml'
  # use_active_relabelling: True
  output_directory: 'SelectorResults/cifar10idn/vanilla_model/val'

