device: cuda
cudnn:
  benchmark: True
  deterministic: True
dataset:
  name: IMAGENETDOGS
  noise_temperature: 2.0
  noise_rate: 0.2
  n_classes: 120
  image_size: 224
preprocess:
  use_resize: True
  resize: 224
model:
  type: cxr
  name: resnet50
train:
  use_balanced_sampler: True
  pretrained: False
  seed: 1
  batch_size: 64
  optimizer: adam
  base_lr: 1e-3
  output_dir: imagenetdogs_noise_20_scratch/vanilla_model
  log_period: 10
  checkpoint_period: 100
  dataloader:
    num_workers: 8
    drop_last: False
    pin_memory: False
validation:
  batch_size: 128
  dataloader:
    num_workers: 8
    drop_last: False
    pin_memory: False
scheduler:
  epochs: 250
  type: cosine
  lr_min_factor: 1e-3
  warmup:
    epochs: 10
    type: linear
    start_factor: 1e-3
augmentation:
  use_random_crop: True
  use_random_horizontal_flip: True
  use_label_smoothing: False
  use_random_affine: True
  use_random_color: False
  random_crop:
    padding: 4
    padding_mode: reflect
  random_horizontal_flip:
    prob: 0.3
  random_affine:
    max_angle: 15
    max_horizontal_shift: 0.05
    max_vertical_shift: 0.05
    max_shear: 5

