#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=InstallEnvironment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=00:30:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

cd $HOME/al-label-cleaning/

# conda create -n alclean python=3.10 --yes

source activate alclean
srun python3 -m pip install -r requirements.txt

srun python3 -m pip install -e .