selector:
  type: ['PosteriorBasedSelectorJoint'] # 'PosteriorBasedSelectorJoint', 'PosteriorBasedSelector', 'BaldSelector'
  model_name: 'Vanilla'
  model_config_path: 'AL_cleaning/configs/models/imagenetdogs_noise_20/resnet_vanilla.yaml'
  use_active_relabelling: True
  output_directory: 'SelectorResults/imagenetdogs_noise_20/vanilla/PosteriorBasedSelectorJoint/train'

